# Generated by Django 4.1.7 on 2023-04-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="qr_code",
            field=models.ImageField(blank=True, upload_to="qr_codes"),
        ),
    ]
