# Generated by Django 4.1.7 on 2023-04-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_delete_customuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="StateUserPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "State User Permission",
                "verbose_name_plural": "State User Permissions",
                "permissions": (
                    ("can_view_report", "Can view report"),
                    ("can_view_profile", "Can view profile"),
                ),
            },
        ),
    ]
