# Generated by Django 4.1.7 on 2023-04-21 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0008_stateuserpermission"),
    ]

    operations = [
        migrations.DeleteModel(name="StateUserPermission",),
    ]
