# Generated by Django 4.1.7 on 2023-04-21 12:46

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("backend", "0009_delete_stateuserpermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": [],},
            bases=("auth.user",),
            managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
    ]
