# Generated by Django 4.1.7 on 2023-04-21 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0010_customuser"),
    ]

    operations = [
        migrations.DeleteModel(name="CustomUser",),
    ]
