# Generated by Django 4.1.7 on 2023-04-26 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0012_asset_item_creation_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetcategory",
            name="item_creation_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
