# Generated by Django 4.1.7 on 2023-04-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0013_assetcategory_item_creation_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="remark",
            field=models.TextField(blank=True, null=True),
        ),
    ]
