# Generated by Django 4.1.7 on 2023-04-27 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0015_report_item_creation_date"),
    ]

    operations = [
        migrations.RemoveField(model_name="report", name="enrollment_number",),
    ]
