# Generated by Django 4.1.7 on 2023-05-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0016_remove_report_enrollment_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetcategory",
            name="category_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
