# Generated by Django 4.1.7 on 2023-05-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0017_alter_assetcategory_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="service_type",
            field=models.CharField(default="none", max_length=100),
        ),
    ]
