# Generated by Django 4.1.7 on 2023-05-19 15:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0018_report_service_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="item_creation_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
