# Generated by Django 4.1.7 on 2023-05-30 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_alter_asset_item_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='sub_category',
        ),
    ]
