# Generated by Django 4.1.7 on 2023-06-01 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_reportlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportlog',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.report'),
        ),
    ]
